### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by umpirsky** [docteurklein/funk-spec#5]
In readme, there is 404 image https://camo.githubusercontent.com/d8835fc70d49dc49a5fbbef5cf7e04359f27b669/68747470733a2f2f726177322e6769746875622e636f6d2f646f63746575726b6c65696e2f66756e6b2d737065632f6d61737465722f66756e6b2e706e67.

**Comment by stof** [comment]
The original URL path (before being replaced by the github proxy to be sure it does not end with mixed content) is https://raw2.github.com/docteurklein/funk-spec/master/funk.png
I guess such URL is not valid anymore (raw2 looks weird btw)

**Comment by docteurklein** [comment]
Thanks I fixed it.
